package org.example.backendadventure.model.login;

import jakarta.persistence.*;

@Entity
public class LoginProfile {

    //***ATTRIBUTES***-------------------------------------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Autogenerated id
    private int id;
    @Column(unique=true)
    private String username;
    @Column(nullable = false)
    private String password;

    //***GETTER & SETTER***---------------------------------------------------------------------------------------------
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    //***END CLASS***---------------------------------------------------------------------------------------------------
}
